package mssqldb

var DatabasePermissions = map[string]string{
	"AADS": "Alter Any Database Event Session",
	"AAMK": "Alter Any Mask",
	"AEDS": "Alter Any External Data Source",
	"AEFF": "Alter Any External File Format",
	"AL":   "Alter",
	"ALAK": "Alter Any Asymmetric Key",
	"ALAR": "Alter Any Application Role",
	"ALAS": "Alter Any Assembly",
	"ALCF": "Alter Any Certificate",
	"ALDS": "Alter Any Dataspace",
	"ALED": "Alter Any Database Event Notification",
	"ALFT": "Alter Any Fulltext Catalog",
	"ALMT": "Alter Any Message Type",
	"ALRL": "Alter Any Role",
	"ALRT": "Alter Any Route",
	"ALSB": "Alter Any Remote Service Binding",
	"ALSC": "Alter Any Contract",
	"ALSK": "Alter Any Symmetric Key",
	"ALSM": "Alter Any Schema",
	"ALSV": "Alter Any Service",
	"ALTG": "Alter Any Database DDL Trigger",
	"ALUS": "Alter Any User",
	"AUTH": "Authenticate",
	"BADB": "Backup Database",
	"BALO": "Backup Log",
	"CL":   "Control",
	"CO":   "Connect",
	"CORP": "Connect Replication",
	"CP":   "Checkpoint",
	"CRAG": "Create Aggregate",
	"CRAK": "Create Asymmetric Key",
	"CRAS": "Create Certificate",
	"CRDB": "Create Fatabase",
	"CRDF": "Create Default",
	"CRED": "Create Database DDL Event Notification",
	"CRFN": "Create Function",
	"CRFT": "Create Fulltext Catalog",
	"CRMT": "Create Message Type",
	"CRPR": "Create Procedure",
	"CRQU": "Create Queue",
	"CRRL": "Create Role",
	"CRRT": "Create Route",
	"CRRU": "Create Rule",
	"CRSB": "Create Remote Service Binding",
	"CRSC": "Create contract",
	"CRSK": "Create symmetric key",
	"CRSM": "Create Schema",
	"CRSN": "Create Synonym",
	"CRSO": "Create Sequence",
	"CRSV": "Create Service",
	"CRTB": "Create Table",
	"CRTY": "Create Type",
	"CRVW": "Create View",
	"CRXS": "Create XML Schema Collection",
	"DL":   "Delete",
	"DABO": "Administer Database Bulk Operations",
	"EAES": "Execute Any External Script",
	"EX":   "Execute",
	"IN":   "Insert",
	"RC":   "Receive Object",
	"RF":   "References",
	"SL":   "Select",
	"SPLN": "Showplan",
	"SUQN": "Subscribe Query Notifications",
	"TO":   "Take Ownership",
	"UP":   "Update",
	"VW":   "View Definition",
	"VWCK": "View Any Column Encryption Key Definition",
	"VWCM": "View Any Column Master Key Definition",
	"VWCT": "View Change Tracking",
	"VWDS": "View Database State Database",
}
