version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=devP@ssw0rd
      - MSSQL_PID=Developer
    network_mode: "host"
    volumes:
      - db:/var/opt/mssql
volumes:
  db:
    driver: local