services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=devP@ssw0rd
      - MSSQL_PID=Developer
    networks:
      - sql
    ports:
      - 1433:1433
    volumes:
      - db:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd","-C -U sa -P 'devP@ssw0rd' -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'" ]
      interval: 10s
      timeout: 10s
      retries: 6

volumes:
  db:
    driver: local

networks:
  sql:
    driver: bridge
